/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mgvaqueiro;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class cadastramento_mgvaqueiro extends javax.swing.JFrame {
    
    String cadastro[][] = new String[10][3];
    int i = 0, x = 0;
    
    /**
     * Creates new form cadastramento_mgvaqueiro
     */
    public cadastramento_mgvaqueiro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cadastropage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homepage = new javax.swing.JPanel();
        cad_name_b = new javax.swing.JLabel();
        prod_name = new javax.swing.JLabel();
        cad_name_v = new javax.swing.JLabel();
        but_start = new javax.swing.JButton();
        chapeu = new javax.swing.JLabel();
        enfeite2 = new javax.swing.JLabel();
        enfeite1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastropage = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        cadastrarnome = new javax.swing.JTextField();
        campo_obrigatorio = new javax.swing.JLabel();
        campo_obrigatorio1 = new javax.swing.JLabel();
        campo_obrigatorio2 = new javax.swing.JLabel();
        cadastrarcidade = new javax.swing.JTextField();
        cadastrarestado = new javax.swing.JTextField();
        but_sair = new javax.swing.JButton();
        but_cadastrar = new javax.swing.JButton();
        but_imprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);

        homepage.setBackground(new java.awt.Color(153, 255, 153));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cad_name_b.setFont(new java.awt.Font("Harlow Solid Italic", 1, 105)); // NOI18N
        cad_name_b.setForeground(new java.awt.Color(255, 255, 255));
        cad_name_b.setText("Cadastro");
        homepage.add(cad_name_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 400, 110));

        prod_name.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        prod_name.setText("MGVAQUEIRO PRODUÇÕES");
        homepage.add(prod_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, 30));

        cad_name_v.setFont(new java.awt.Font("Harlow Solid Italic", 1, 105)); // NOI18N
        cad_name_v.setForeground(new java.awt.Color(0, 153, 51));
        cad_name_v.setText("Cadastro");
        homepage.add(cad_name_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 110));

        but_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/start.png"))); // NOI18N
        but_start.setContentAreaFilled(false);
        but_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_startActionPerformed(evt);
            }
        });
        homepage.add(but_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 140));

        chapeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chapeu.png"))); // NOI18N
        homepage.add(chapeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 90));

        enfeite2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfeite2.png"))); // NOI18N
        homepage.add(enfeite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 140, 170));

        enfeite1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfeite 1.png"))); // NOI18N
        homepage.add(enfeite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        homepage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        homepage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 420, 410));

        cadastropage.setBackground(new java.awt.Color(153, 255, 153));
        cadastropage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        nome.setText("NOME:");
        cadastropage.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        cidade.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        cidade.setText("CIDADE:");
        cadastropage.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        estado.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        estado.setText("ESTADO:");
        cadastropage.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        cadastrarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarnomeActionPerformed(evt);
            }
        });
        cadastrarnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarnomeKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 350, -1));

        campo_obrigatorio.setForeground(new java.awt.Color(255, 0, 51));
        campo_obrigatorio.setText("*campo obrigatório");
        cadastropage.add(campo_obrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        campo_obrigatorio1.setForeground(new java.awt.Color(255, 0, 51));
        campo_obrigatorio1.setText("*campo obrigatório");
        cadastropage.add(campo_obrigatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        campo_obrigatorio2.setForeground(new java.awt.Color(255, 0, 51));
        campo_obrigatorio2.setText("*campo obrigatório");
        cadastropage.add(campo_obrigatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        cadastrarcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarcidadeKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 340, -1));

        cadastrarestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarestadoKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 340, -1));

        but_sair.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        but_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-web (1).png"))); // NOI18N
        but_sair.setText("SAIR");
        but_sair.setContentAreaFilled(false);
        but_sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        but_sair.setVerifyInputWhenFocusTarget(false);
        but_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_sairActionPerformed(evt);
            }
        });
        cadastropage.add(but_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 40));

        but_cadastrar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        but_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-web (1).png"))); // NOI18N
        but_cadastrar.setText("CADASTRAR");
        but_cadastrar.setContentAreaFilled(false);
        but_cadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        but_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cadastrarActionPerformed(evt);
            }
        });
        cadastropage.add(but_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 60));

        but_imprimir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        but_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-web (1).png"))); // NOI18N
        but_imprimir.setText("IMPRIMIR");
        but_imprimir.setContentAreaFilled(false);
        but_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        but_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_imprimirActionPerformed(evt);
            }
        });
        cadastropage.add(but_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 130, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        cadastropage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, 370));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        cadastropage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 420, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cadastropage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(cadastropage, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_startActionPerformed
        homepage.setVisible(false);
        cadastropage.setVisible(true);
    }//GEN-LAST:event_but_startActionPerformed

    private void cadastrarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarnomeActionPerformed

    private void but_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_but_sairActionPerformed

    private void but_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cadastrarActionPerformed
       cadastrarnome.requestFocus();
        if (cadastrarnome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu nome.");
            cadastrarnome.requestFocus();
            cadastrarnome.setForeground(Color.red);
            nome.setForeground(Color.red);
            
        } else if (cadastrarcidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe sua cidade.");
            cadastrarcidade.requestFocus();
            cadastrarcidade.setForeground(Color.red);
            cidade.setForeground(Color.red);
            
        } else if (cadastrarestado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu estado.");
            cadastrarestado.requestFocus();
            cadastrarestado.setForeground(Color.red);
            estado.setForeground(Color.red);

            } else {
            cadastro[i][x] = cadastrarnome.getText();
            x++;
            cadastro[i][x] = cadastrarcidade.getText();
            x++;
            cadastro[i][x] = cadastrarestado.getText();
            x = 0;
            i++;
            JOptionPane.showMessageDialog(this, "Cadastramento feito!");
            cadastrarnome.setText(null);
            cadastrarcidade.setText(null);
            cadastrarestado.setText(null);

        }

    }//GEN-LAST:event_but_cadastrarActionPerformed

    private void cadastrarnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarnomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarcidade.requestFocus();
        }
    }//GEN-LAST:event_cadastrarnomeKeyPressed

    private void cadastrarcidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarcidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarestado.requestFocus();
        }
    }//GEN-LAST:event_cadastrarcidadeKeyPressed

    private void cadastrarestadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarestadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarnome.requestFocus();
        }
    }//GEN-LAST:event_cadastrarestadoKeyPressed

    private void but_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_imprimirActionPerformed
        String todos_cadastros = "";
        for (int a = 0; a < i; a++) {
           todos_cadastros += "Nome: " + cadastro[a][0] + "\nCidade: " + cadastro[a][1] + "\nEstado: " + cadastro[a][2] + "\n\n";
        }
        JOptionPane.showMessageDialog(null, todos_cadastros);           
    }//GEN-LAST:event_but_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastramento_mgvaqueiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastramento_mgvaqueiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastramento_mgvaqueiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastramento_mgvaqueiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastramento_mgvaqueiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_cadastrar;
    private javax.swing.JButton but_imprimir;
    private javax.swing.JButton but_sair;
    private javax.swing.JButton but_start;
    private javax.swing.JLabel cad_name_b;
    private javax.swing.JLabel cad_name_v;
    private javax.swing.JTextField cadastrarcidade;
    private javax.swing.JTextField cadastrarestado;
    private javax.swing.JTextField cadastrarnome;
    private javax.swing.JPanel cadastropage;
    private javax.swing.JLabel campo_obrigatorio;
    private javax.swing.JLabel campo_obrigatorio1;
    private javax.swing.JLabel campo_obrigatorio2;
    private javax.swing.JLabel chapeu;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel enfeite1;
    private javax.swing.JLabel enfeite2;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel prod_name;
    // End of variables declaration//GEN-END:variables
}
