package cadastramento;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Maique
 */
public class cadastro extends javax.swing.JFrame {

    String cadastro[][] = new String[10][3];
    int i = 0, x = 0;

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cadastropage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastropage = new javax.swing.JPanel();
        cadastrarnome = new javax.swing.JTextField();
        cadastrarcidade = new javax.swing.JTextField();
        cadastrarestado = new javax.swing.JTextField();
        jLabelcidade = new javax.swing.JLabel();
        jLabelestado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelnome = new javax.swing.JLabel();
        homepage = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastropage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarnomeActionPerformed(evt);
            }
        });
        cadastrarnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarnomeKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 260, 34));

        cadastrarcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarcidadeKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, 34));

        cadastrarestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarestadoKeyPressed(evt);
            }
        });
        cadastropage.add(cadastrarestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 260, 37));

        jLabelcidade.setText("CIDADE");
        cadastropage.add(jLabelcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelestado.setText("ESTADO");
        cadastropage.add(jLabelestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        cadastropage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jButton2.setText("cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        cadastropage.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jButton3.setText("imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        cadastropage.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabelnome.setText("NOME:");
        cadastropage.add(jLabelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        getContentPane().add(cadastropage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        homepage.setBackground(new java.awt.Color(153, 255, 153));
        homepage.setForeground(new java.awt.Color(102, 153, 0));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-de-inicio (1).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        homepage.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 1, 105)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro");
        homepage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 110));

        jLabel2.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel2.setText("MGVAQUEIRO PRODUÇÕES");
        homepage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, 30));

        jLabel3.setFont(new java.awt.Font("Harlow Solid Italic", 1, 105)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Cadastro");
        homepage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vaqueiro.png"))); // NOI18N
        homepage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        getContentPane().add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 480, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarnomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cadastrarnome.requestFocus();
        if (cadastrarnome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu nome.");
            cadastrarnome.requestFocus();
            cadastrarnome.setForeground(Color.red);
            jLabelnome.setForeground(Color.red);

        } else if (cadastrarcidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe sua cidade.");
            cadastrarcidade.requestFocus();
            cadastrarcidade.setForeground(Color.red);
            jLabelcidade.setForeground(Color.red);

        } else if (cadastrarestado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu estado.");
            cadastrarestado.requestFocus();
            cadastrarestado.setForeground(Color.red);
            jLabelestado.setForeground(Color.red);

        } else {
            cadastro[i][x] = cadastrarnome.getText();
            x++;
            cadastro[i][x] = cadastrarcidade.getText();
            x++;
            cadastro[i][x] = cadastrarestado.getText();
            x = 0;
            i++;
            JOptionPane.showMessageDialog(this, "Cadastramento feito!");
            cadastrarnome.setText(null);
            cadastrarcidade.setText(null);
            cadastrarestado.setText(null);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cadastrarnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarnomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarcidade.requestFocus();
        }
    }//GEN-LAST:event_cadastrarnomeKeyPressed

    private void cadastrarcidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarcidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarestado.requestFocus();
        }
    }//GEN-LAST:event_cadastrarcidadeKeyPressed

    private void cadastrarestadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarestadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarnome.requestFocus();
        }
    }//GEN-LAST:event_cadastrarestadoKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String todos_cadastros = " ";
        for (i = 0; i < cadastro.length; i++) {
            for (x = 0; x < 3; x++) {
                todos_cadastros += cadastro[i][x];
                todos_cadastros += "  ";
            }
            todos_cadastros += "\n";
        }
        JOptionPane.showMessageDialog(null, todos_cadastros);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        homepage.setVisible(false);
        cadastropage.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadastrarcidade;
    private javax.swing.JTextField cadastrarestado;
    private javax.swing.JTextField cadastrarnome;
    private javax.swing.JPanel cadastropage;
    private javax.swing.JPanel homepage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelcidade;
    private javax.swing.JLabel jLabelestado;
    private javax.swing.JLabel jLabelnome;
    // End of variables declaration//GEN-END:variables
}
